import type { Snapshot } from "@/website-dashboard/types"

function fmt(iso: string) {
  const d = new Date(iso + "T12:00:00Z")
  return d.toLocaleDateString("en-US", { day: "numeric", month: "short" })
}

const STATUS_BAR: Record<string, string> = {
  complete:    "bg-emerald-500",
  in_progress: "bg-amber-400",
  not_started: "bg-muted-foreground/20",
}

export default function DashboardHeader({ snapshot }: { snapshot: Snapshot }) {
  const { meta, overallProgress, phases } = snapshot
  const pct = overallProgress?.productPercentComplete ?? 0
  const year = meta.period.end.split("-")[0]

  return (
    <header className="bg-background border-b border-border px-6 py-10 lg:py-14">
      <div className="max-w-5xl mx-auto">
        <p className="font-mono text-xs text-primary uppercase tracking-widest mb-4">
          // {meta.project}
        </p>

        <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6">
          <div>
            <h1 className="text-3xl lg:text-5xl font-bold text-foreground tracking-tight mb-2">
              Week {meta.week}
              <span className="text-muted-foreground font-normal text-xl lg:text-2xl ml-3">
                {fmt(meta.period.start)} – {fmt(meta.period.end)}, {year}
              </span>
            </h1>
            <p className="font-mono text-xs text-muted-foreground">
              generated by <span className="text-foreground/70">{meta.generatedBy}</span>
              {" · "}
              {new Date(meta.generatedAt).toLocaleDateString("en-US", {
                day: "numeric",
                month: "long",
                year: "numeric",
              })}
            </p>
          </div>

          <div className="flex items-end gap-4">
            <div className="text-right">
              <p className="font-mono text-xs text-muted-foreground uppercase tracking-widest mb-1">
                product complete
              </p>
              <p className="text-6xl lg:text-7xl font-bold leading-none text-primary text-glow">
                {pct}<span className="text-3xl">%</span>
              </p>
            </div>
            {(overallProgress?.weekDelta?.product ?? 0) > 0 && (
              <div className="pb-2">
                <span className="font-mono text-xs px-3 py-1 rounded-sm border border-primary/30 text-primary bg-primary/5">
                  +{overallProgress.weekDelta.product}% this week
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Phase progress bar */}
        <div className="mt-8">
          <div className="flex justify-between mb-2">
            {(["phase1", "phase2", "phase3", "phase4"] as const).map((p, i) => (
              <span key={p} className="font-mono text-xs text-muted-foreground">Phase {i + 1}</span>
            ))}
          </div>
          <div className="h-1.5 bg-muted rounded-full overflow-hidden flex gap-px">
            {(["phase1", "phase2", "phase3", "phase4"] as const).map((p) => {
              const phase = phases?.[p]
              return (
                <div key={p} className="flex-1 relative bg-muted rounded-full overflow-hidden">
                  <div
                    className={`absolute left-0 top-0 h-full rounded-full transition-all ${STATUS_BAR[phase?.status ?? "not_started"]}`}
                    style={{ width: `${phase?.percentComplete ?? 0}%` }}
                  />
                </div>
              )
            })}
          </div>
          <div className="flex justify-between mt-2">
            <span className="font-mono text-xs text-muted-foreground">Start</span>
            <span className="font-mono text-xs text-primary">{pct}% complete</span>
            <span className="font-mono text-xs text-muted-foreground">Launch</span>
          </div>
        </div>
      </div>
    </header>
  )
}
