"use client"

import { useState } from "react"
import type { Snapshot } from "@/website-dashboard/types"
import DashboardHeader from "./DashboardHeader"
import PhaseOverview from "./PhaseOverview"
import GitActivityCard from "./GitActivityCard"
import CodeMetricsCard from "./CodeMetricsCard"
import TestsCard from "./TestsCard"
import PhaseDetail from "./PhaseDetail"
import SecurityReport from "./SecurityReport"
import ArchitectureStatus from "./ArchitectureStatus"
import WeekHighlights from "./WeekHighlights"
import WeeklyTrend from "./WeeklyTrend"

function fmtShort(iso: string) {
  const [, m, d] = iso.split("-")
  const months = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]
  return `${parseInt(d, 10)} ${months[parseInt(m, 10) - 1]}`
}

export default function DashboardShell({ snapshots }: { snapshots: Snapshot[] }) {
  const [selectedIndex, setSelectedIndex] = useState(snapshots.length - 1)
  const snapshot = snapshots[selectedIndex]

  return (
    <>
      <DashboardHeader snapshot={snapshot} />

      {snapshots.length > 1 && (
        <div className="bg-background border-b border-border">
          <div className="max-w-7xl mx-auto px-4 lg:px-8">
            <div className="flex gap-2 overflow-x-auto py-3">
              {snapshots.map((s, i) => (
                <button
                  key={s.meta.week}
                  onClick={() => setSelectedIndex(i)}
                  className={`shrink-0 font-mono text-xs px-4 py-1.5 rounded-sm border transition-colors whitespace-nowrap
                    ${i === selectedIndex
                      ? "text-primary-foreground bg-primary border-primary"
                      : "text-muted-foreground bg-transparent border-border hover:border-primary/40 hover:text-foreground"
                    }`}
                >
                  Week {s.meta.week}
                  <span className="ml-1.5 opacity-60">
                    {fmtShort(s.meta.period.start)}–{fmtShort(s.meta.period.end)}
                  </span>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      <div className="max-w-7xl mx-auto px-4 lg:px-8 py-12 space-y-12">
        <PhaseOverview snapshot={snapshot} />

        <div className="grid lg:grid-cols-2 gap-6">
          {snapshot.git && <GitActivityCard git={snapshot.git} />}
          {snapshot.codeMetrics && <CodeMetricsCard metrics={snapshot.codeMetrics} />}
        </div>

        {snapshot.tests && (
          <div className="grid lg:grid-cols-2 gap-6">
            <TestsCard tests={snapshot.tests} />
          </div>
        )}

        {snapshot.phases && <PhaseDetail phases={snapshot.phases} />}

        {snapshot.security && <SecurityReport security={snapshot.security} />}

        {snapshot.architecture && <ArchitectureStatus snapshot={snapshot} />}

        {snapshot.weekHighlights && <WeekHighlights snapshot={snapshot} />}

        <WeeklyTrend snapshots={snapshots} />
      </div>

      <footer className="border-t border-border mt-16 py-10 text-center space-y-2">
        <p className="font-mono text-xs text-muted-foreground">
          Generated by{" "}
          <span className="text-foreground/70">{snapshot.meta.generatedBy}</span>
          {" · "}
          {new Date(snapshot.meta.generatedAt).toLocaleDateString("en-US", {
            weekday: "long",
            day: "numeric",
            month: "long",
            year: "numeric",
          })}
        </p>
        <p className="font-mono text-xs text-primary/40">
          {snapshot.meta.project} Dev Dashboard
        </p>
      </footer>
    </>
  )
}
